// Generated by CoffeeScript 1.8.0
(function() {
  this.config = {
    templateBaseUrl: '/views/',
    useHtml5Mode: false,
    projectSheetTemplateSlug: 'is',
    defaultSiteTags: ['consocollab'],
    editorialSuggestedTags: ['alimentation', 'équipements', 'mobilité', 'services', 'tourisme-hébergements', 'culture'],
    defaultResultLimit: 100,
    bucket_uri: 'http://data.patapouf.org/bucket/upload/',
    loginBaseUrl: 'http://data.patapouf.org/api/v0',
    oauthBaseUrl: 'http://bretagne.initiative.place',
    oauthCliendId: '834927693290-fdibik9cv2ngiqpdn47qjlc1tqp97cl2.apps.googleusercontent.com',
    media_uri: 'http://data.patapouf.org',
    rest_uri: "http://data.patapouf.org/api/v0",
    dataserver_url: "http://data.patapouf.org"
  };

}).call(this);
