# Site settings
title: Consommation Collaborative
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  La consommation collaborative en Bretagne
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bretagne.initiative.place" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
logo: 
# Build settings
markdown: kramdown
